### ISSUE TITLE
section_manager.sh

### ISSUE THREAD

**Issue by Zignet64** [teqnodude/glftpd-installer#4]
Hello teqnodude,

I'm having fun thanks again :)
Have questions about the internal script to manage section : ./section_manager.sh

```
What section do you want to manage, if not listed just type it in : **test**
What do you wanna do with **TEST** ? [A]dd [R]remove, default A : 
```

Why force uppercase ? 
`section=${section^^}`
if i want keep **section case**, can i comment the line without causing any problems afterwards ?

----------

And if i remove all dated section (for my example 0DAY and MP3) is it possible to disable also the automatic script for the today dir creation at midnight ?
Have no more section 0DAY and MP3 but a script force creation at midnight. 

```
eggdrop partyline :
[01:00:02] [ngBot] Error :: "variables(TURDAYC)" not defined in the config, type becomes "DEFAULT".
[01:00:02] [ngBot] Error :: "variables(TURDAYC)" not defined in the config, type becomes "DEFAULT".

/glftp/site/
lrwxrwxrwx  1 root root   11 Jan  2 00:00 '!Today_0DAY' -> ./0DAY/0102
lrwxrwxrwx  1 root root   10 Jan  2 00:00 '!Today_MP3' -> ./MP3/0102
drwxr-xr-x  3 root root 4096 Jan  2 00:00  0DAY
drwxr-xr-x  3 root root 4096 Jan  2 00:00  MP3
```

**Comment by teqnodude** [comment]
"Why force uppercase ?"

Because in my view it looks much better with having dirnames in all uppercase based on the reasoning that releases are of mixed upper/lowercase and filenames are in all lowercase so it's a way of creating distinction between sections, releases and files in the way things look.

"if i want keep section case, can i comment the line without causing any problems afterwards ?"

Yes that is enough and it shouldn't cause future problems

"And if i remove all dated section (for my example 0DAY and MP3) is it possible to disable also the automatic script for the today dir creation at midnight ?
Have no more section 0DAY and MP3 but a script force creation at midnight."

I can look it into it, only requires a removal of a line in crontab to disable the execution of the script.

**Comment by teqnodude** [comment]
I have included the check for dated sections which removes the line in crontab. Closing this issue.

**Comment by Zignet64** [comment]
Thanks for answers and fix !! :)

**Comment by gngrn1nja** [comment]
Great script, I’ve been using glFTPd for a good bit and this makes spinning up a new server super easy!
