### ISSUE TITLE
pzs-ng : sorted by .... doesnt work

### ISSUE THREAD

**Issue by Argon-D** [teqnodude/glftpd-installer#5]
Hi first of all thank you so much for this amazing installer it's very helpfull. Unfortunately i have 2 big issue and i hope you can help and fix because a tried for many hours without any progression.. :(

The first one is about sorted by genre/artist/years MP3 
I created the folder by my hand inside /site folder and set properly the path in  zsconfig.h 
 ("/site/sorted.by.genre") but after i logged into my ftp those fodlers are empyt every time and dont link the mp3 folder by genre, artist or years :(

The second one problem is PRETIME on NEW folder doesnt start , nothing happen when someone create new folder on ftp.

Maybe those 2 error are linked i dont know ... :S I notice after the installation pzs-ng fodler is inside Backup folder , it's normal?

thank you again for this work and for your possible reply !

**Comment by teqnodude** [comment]
I have chosen to put pzs-ng source folder under /glftpd/backup so it's not a mistake. 

To have mp3's sorted you need to set path correctly AND enable sorting and recompile pzs-ng, sorting of mp3's will then happen on all new mp3 uploads.  To recompile you go to /glftpd/backup/pzs-ng and type make distclean && ./configure && make && make install

Example settings for MP3 sorting:
#define audio_genre_path                "/site/MUSIC.BY.GENRE/"
#define audio_artist_path               "/site/MUSIC.BY.ARTIST/"
#define audio_year_path                 "/site/MUSIC.BY.YEAR/"
#define audio_group_path                "/site/MUSIC.BY.GROUP/"
#define audio_artist_sort_various_only  FALSE
#define audio_genre_sort                TRUE
#define audio_year_sort                 FALSE
#define audio_artist_sort               TRUE
#define audio_artist_noid3              TRUE
#define audio_group_sort                FALSE

To sort all previous uploads then you need to use this script and run it in shell with $onlysort = 1 option. 
https://github.com/pzs-ng/scripts/blob/master/total-rescan/total-rescan.pl

If you have issues with pzs-ng then I suggest you contact the developers of that since that has nothing to do with the installer.

Regarding PRETIME then there is no predb bot in the installer.

**Comment by Argon-D** [comment]
thank you so much for the quickly reply . Now mp3 sorted woooorks!! thxxxx again :)
