### ISSUE TITLE
Problem with devises /dev/sda1 to another /dev/sdb1

### ISSUE THREAD

**Issue by ghost** [teqnodude/glftpd-installer#6]
Hey

First of all i Will say fucking awesome script :-)

I have a problem with devises /dev/sda1 how do i change it to my Big storeage  /dev/sdb1 i have checked it 10 times today but no luck evertime i try INSTALL it on storage it keeps installing in rootdir :-(

Do you have any solution for it ?

**Comment by d3vils** [comment]
You need to pick the path you want to install it to when the installer ask you where you would like to install it.

**Comment by ghost** [comment]
Where are what i have in dev /sdb1. When i ask for path i put in /dev/sdb1 but nothing happens and it INSTALL in rootdir insted

dev/sdb1        80T   40K   79T   1% /home

**Comment by d3vils** [comment]
when it ask for the path put /home/glftpd

**Comment by ghost** [comment]
usr/sbin not found in environmental PATH
Default PATH should be : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Current PATH is : /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
Correcting PATH
Done

It comes evertime cant do nothing should i pico INSTALL.sh and change something in the file ?

**Comment by teqnodude** [comment]
I have intentionally put the install path to /glftpd on sys hdd because most scripts are configured for that path to avoid future problems. The question regarding what device to use for /glftpd/site is related to !free/!df in pzs-ng and tur-space. 

If you want to install to any other path than /glftpd then you will need to edit line 15 in install.sh
`glroot="/glftpd"`
just remember that the cleanup.sh script will not work properly if changing this line and needs to be updated with proper paths.
