### ISSUE TITLE
irc channels and Section how many i can make please help :-)

### ISSUE THREAD

**Issue by ghost** [teqnodude/glftpd-installer#7]
Hi

i have a question with the installer.sh

when i installed it i change how many sections i need for my site so i changed it to 10-30 section but when i do install.sh and comes to section then i type in fx 15 it says need a lower number and anfter i come to 3 i can do my section 

same as how many Irc channels i want are the same question 
-------------------------------------------------------------------------------------------------------------
SECTION

## how many sections
function section_names
{
        if [ ! -d ".tmp" ] 
        then
                mkdir .tmp
        fi
        
        if [[ -f "$cache" && "`cat $cache | grep -w sections | wc -l`" = 1 ]]
        then
                sections=`cat $cache | grep -w sections | cut -d "=" -f2 | tr -d "\""`
        else
                echo
                echo "Valid Sections are : "
                echo "0DAY ARCHIVE FOREIGN ANIME APPS-WINDOWS APPS-LINUX APPS-APPLE DVDR FLAC PC-GAMES MP3 MBLURAY MVDVDR NSW PDA WII PS1 PS2 PS3 PS4 TV-HD TV-DK TV-NORDIC TV-X264 TV-SD X264 X265-2160 XVID-DANISH XVID-NORDIC XVID XXX-N$
                echo
                while [[ -z $sections || $sections != [10-30] ]]
                do
                        echo -n "How many sections do you require for your site ? : " ; read sections
                done
                echo
---------------------------------------------------------------------------------------------------------
IRC CHANNELS

echo
                channelnr=`cat $cache | grep -w channelnr | cut -d "=" -f2 | tr -d "\""`
        else
                while [[ -z $channelnr || "$channelnr" != [10-15] ]]
                do
                        echo -n "How many channels do you require the bot to be in ? : " ; read channelnr
                done

**Comment by teqnodude** [comment]
This is a typical question that goes beyond my installer and have more to do with your personal version of the installer related to your own code. Be aware that in the future I will just close the issue since it's not something that is related to my version. That said, I will help answering your question this time.

Change 
`$sections != [10-30]`
To
`$sections -gt 30`
That makes it repeat the question if you enter a number larger than 30 or any letter

Change
`"$channelnr" != [10-15]`
To
`$channelnr -gt 15`
That makes it repeat the question if you enter a number larger than 15 or any letter

In the latest version of the installer I have increased the limits for sections to 20 and channels to 15. Here are the latest changes: https://github.com/teqnodude/glftpd-installer/commit/26fb022caa0593318f28745d1cb76cd8374addcb

You should be aware that why I have the sections limited is because they are connected to other parts of the installer which is not visible like auto-generation of rules for the sections listed. If you break this by introducing other sectionnames then you will get errors during the installation and it may break the installer altogether.
