### ISSUE TITLE
help to change to more folders in script 

### ISSUE THREAD

**Issue by ghost** [teqnodude/glftpd-installer#8]
Hey Teq

how do i add more folder to the script i need some NORDIC folders when i try add some to the line with all the different folders and when i run ./install.sh and i shall type in folders then it says if not to find  

echo "0DAY ANIME APPS DVDR FLAC GAMES MP3 MBLURAY MVDVDR NSW PDA PS4 TV-HD TV-NL TV-SD X264 X265-2160 XVID XXX XXX-PAYSITE"

**Comment by teqnodude** [comment]
You can't create sections named other than what is being highlighted because the sections highlighted are linked with auto-generation of rules. This is where my section_manager.sh comes in to the picture which I have included in the installer by default meaning it gets installed in the background and you can find it in /glftpd/section_manager.sh, view settings of the file before running it.

Note: No rules are auto-generated by section_manager and needs to manually be created and put in /glftpd/ftp-data/misc/site.rules with the new section name added to /glftpd/bin/tur-rules.sh

If you want to modify the installer to support more sections then you need to modify these things. 

These line need to include the new sections
`echo "0DAY ANIME APPS DVDR FLAC GAMES MP3 MBLURAY MVDVDR NSW PDA PS4 TV-HD TV-NL TV-SD X264 X265-2160 XVID XXX XXX-PAYSITE" `

`0DAY|ANIME|APPS|DVDR|FLAC|GAMES|MP3|MBLURAY|MVDVDR|NSW|PDA|PS4|TV-HD|TV-NL|TV-SD|X264|X265-2160|XVID|XXX|XXX-PAYSITE) `

`while [[ ${section^^} != @(0DAY|ANIME|APPS|DVDR|FLAC|GAMES|MP3|MBLURAY|MVDVDR|NSW|PDA|PS4|TV-HD|TV-NL|TV-SD|X264|X265-2160|XVID|XXX|XXX-PAYSITE) ]] `

This file need to include new rules for the new sections
packages/scripts/tur-rules/rulesgen.sh
